// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql"
	"time"
)

type Account struct {
	ID         int64        `json:"id"`
	Email      string       `json:"email"`
	Password   string       `json:"password"`
	Name       string       `json:"name"`
	IsValid    bool         `json:"is_valid"`
	VerifiedAt sql.NullTime `json:"verified_at"`
	CreatedAt  time.Time    `json:"created_at"`
	UpdatedAt  time.Time    `json:"updated_at"`
}

type AccountValidTemp struct {
	ID        int64     `json:"id"`
	AccountID int64     `json:"account_id"`
	Code      string    `json:"code"`
	CreatedAt time.Time `json:"created_at"`
	ExpiredAt time.Time `json:"expired_at"`
}

type Product struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	Price     string    `json:"price"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type RecommendProduct struct {
	ID        int64     `json:"id"`
	ProductID int64     `json:"product_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
